/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as DijitalIkizRouteImport } from './routes/dijital-ikiz'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UrunlerSlugRouteImport } from './routes/urunler.$slug'
import { Route as AdminUrunlerRouteImport } from './routes/admin.urunler'
import { Route as AdminSiparislerRouteImport } from './routes/admin.siparisler'
import { Route as AdminSceneRouteImport } from './routes/admin.scene'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminMedyaRouteImport } from './routes/admin.medya'
import { Route as AdminMarkalarRouteImport } from './routes/admin.markalar'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminAyarlarRouteImport } from './routes/admin.ayarlar'
import { Route as AdminAltKategorilerRouteImport } from './routes/admin.alt-kategoriler'

const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const DijitalIkizRoute = DijitalIkizRouteImport.update({
  id: '/dijital-ikiz',
  path: '/dijital-ikiz',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UrunlerSlugRoute = UrunlerSlugRouteImport.update({
  id: '/urunler/$slug',
  path: '/urunler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUrunlerRoute = AdminUrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiparislerRoute = AdminSiparislerRouteImport.update({
  id: '/siparisler',
  path: '/siparisler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSceneRoute = AdminSceneRouteImport.update({
  id: '/scene',
  path: '/scene',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedyaRoute = AdminMedyaRouteImport.update({
  id: '/medya',
  path: '/medya',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarkalarRoute = AdminMarkalarRouteImport.update({
  id: '/markalar',
  path: '/markalar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAyarlarRoute = AdminAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAltKategorilerRoute = AdminAltKategorilerRouteImport.update({
  id: '/alt-kategoriler',
  path: '/alt-kategoriler',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dijital-ikiz': typeof DijitalIkizRoute
  '/iletisim': typeof IletisimRoute
  '/admin/alt-kategoriler': typeof AdminAltKategorilerRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markalar': typeof AdminMarkalarRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/scene': typeof AdminSceneRoute
  '/admin/siparisler': typeof AdminSiparislerRoute
  '/admin/urunler': typeof AdminUrunlerRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dijital-ikiz': typeof DijitalIkizRoute
  '/iletisim': typeof IletisimRoute
  '/admin/alt-kategoriler': typeof AdminAltKategorilerRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markalar': typeof AdminMarkalarRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/scene': typeof AdminSceneRoute
  '/admin/siparisler': typeof AdminSiparislerRoute
  '/admin/urunler': typeof AdminUrunlerRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dijital-ikiz': typeof DijitalIkizRoute
  '/iletisim': typeof IletisimRoute
  '/admin/alt-kategoriler': typeof AdminAltKategorilerRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/markalar': typeof AdminMarkalarRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/scene': typeof AdminSceneRoute
  '/admin/siparisler': typeof AdminSiparislerRoute
  '/admin/urunler': typeof AdminUrunlerRoute
  '/urunler/$slug': typeof UrunlerSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dijital-ikiz'
    | '/iletisim'
    | '/admin/alt-kategoriler'
    | '/admin/ayarlar'
    | '/admin/contact'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/markalar'
    | '/admin/medya'
    | '/admin/projects'
    | '/admin/scene'
    | '/admin/siparisler'
    | '/admin/urunler'
    | '/urunler/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dijital-ikiz'
    | '/iletisim'
    | '/admin/alt-kategoriler'
    | '/admin/ayarlar'
    | '/admin/contact'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/markalar'
    | '/admin/medya'
    | '/admin/projects'
    | '/admin/scene'
    | '/admin/siparisler'
    | '/admin/urunler'
    | '/urunler/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dijital-ikiz'
    | '/iletisim'
    | '/admin/alt-kategoriler'
    | '/admin/ayarlar'
    | '/admin/contact'
    | '/admin/homepage'
    | '/admin/login'
    | '/admin/markalar'
    | '/admin/medya'
    | '/admin/projects'
    | '/admin/scene'
    | '/admin/siparisler'
    | '/admin/urunler'
    | '/urunler/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DijitalIkizRoute: typeof DijitalIkizRoute
  IletisimRoute: typeof IletisimRoute
  UrunlerSlugRoute: typeof UrunlerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dijital-ikiz': {
      id: '/dijital-ikiz'
      path: '/dijital-ikiz'
      fullPath: '/dijital-ikiz'
      preLoaderRoute: typeof DijitalIkizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/urunler/$slug': {
      id: '/urunler/$slug'
      path: '/urunler/$slug'
      fullPath: '/urunler/$slug'
      preLoaderRoute: typeof UrunlerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/urunler': {
      id: '/admin/urunler'
      path: '/urunler'
      fullPath: '/admin/urunler'
      preLoaderRoute: typeof AdminUrunlerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/siparisler': {
      id: '/admin/siparisler'
      path: '/siparisler'
      fullPath: '/admin/siparisler'
      preLoaderRoute: typeof AdminSiparislerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scene': {
      id: '/admin/scene'
      path: '/scene'
      fullPath: '/admin/scene'
      preLoaderRoute: typeof AdminSceneRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medya': {
      id: '/admin/medya'
      path: '/medya'
      fullPath: '/admin/medya'
      preLoaderRoute: typeof AdminMedyaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/markalar': {
      id: '/admin/markalar'
      path: '/markalar'
      fullPath: '/admin/markalar'
      preLoaderRoute: typeof AdminMarkalarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ayarlar': {
      id: '/admin/ayarlar'
      path: '/ayarlar'
      fullPath: '/admin/ayarlar'
      preLoaderRoute: typeof AdminAyarlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alt-kategoriler': {
      id: '/admin/alt-kategoriler'
      path: '/alt-kategoriler'
      fullPath: '/admin/alt-kategoriler'
      preLoaderRoute: typeof AdminAltKategorilerRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAltKategorilerRoute: typeof AdminAltKategorilerRoute
  AdminAyarlarRoute: typeof AdminAyarlarRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMarkalarRoute: typeof AdminMarkalarRoute
  AdminMedyaRoute: typeof AdminMedyaRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSceneRoute: typeof AdminSceneRoute
  AdminSiparislerRoute: typeof AdminSiparislerRoute
  AdminUrunlerRoute: typeof AdminUrunlerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAltKategorilerRoute: AdminAltKategorilerRoute,
  AdminAyarlarRoute: AdminAyarlarRoute,
  AdminContactRoute: AdminContactRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMarkalarRoute: AdminMarkalarRoute,
  AdminMedyaRoute: AdminMedyaRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSceneRoute: AdminSceneRoute,
  AdminSiparislerRoute: AdminSiparislerRoute,
  AdminUrunlerRoute: AdminUrunlerRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DijitalIkizRoute: DijitalIkizRoute,
  IletisimRoute: IletisimRoute,
  UrunlerSlugRoute: UrunlerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
